### PR TITLE
Allow multiple comma-separated domains

### PR DESCRIPTION
**Pull request by fiksn**
The idea is that if you just upgrade to this version everything should work as before. However instead of just one domain you can now include a comma-seperated list in DOMAIN.

Actually this is a group effort - I'd like to thank @aljazceru for the initiative and testing and @zwx00 for the CSS improvements (my change used to have a suffix-hack class).

### CODE REVIEW

**Comment by aljazceru** [comment]
you can see it in action at https://lnaddress.me/

**Comment by fiatjaf** [comment]
Very cool! Thanks!

**Comment by fiatjaf** [comment]
Looks good, except for the fact that when I created an address fiatjaf@lnaddress.me it generated the test invoice with this description:

> lnaddress.me,lnaddress.net,lightning.by's PIN for 'fiatjaf@lnaddress.me,lnaddress.net,lightning.by' lightning address: f9ea9890556dc5326e857c7f5c84c190cebe8d0b3859549efddcdb3bc08df012

**Comment by fiksn** [comment]
Nice find, I should have done `grep  "s\.Domain" *`. Should be better now.

**Pull request merged**
